<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit078120e19ef65ab612c6a57602ef2c35
{
    public static $prefixLengthsPsr4 = array (
        'G' => 
        array (
            'GameQ\\' => 6,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'GameQ\\' => 
        array (
            0 => __DIR__ . '/..' . '/austinb/gameq/src/GameQ',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit078120e19ef65ab612c6a57602ef2c35::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit078120e19ef65ab612c6a57602ef2c35::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
